// ═══════════════════════════════════════════════════════════════════════════
// LUMEN — Seamless Thermal Hotspot Isolator
// Preserves the authentic Grad-CAM thermal colors (Red -> Orange -> Yellow -> Green -> Cyan)
// while making the cold blue/purple background and mask boundary completely transparent.
// ═══════════════════════════════════════════════════════════════════════════

const processedCache = new Map();

export async function createCleanThermalOverlay(imageSrc) {
  if (!imageSrc) return "";
  if (processedCache.has(imageSrc)) {
    return processedCache.get(imageSrc);
  }

  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      try {
        const canvas = document.createElement("canvas");
        const w = img.naturalWidth || img.width || 512;
        const h = img.naturalHeight || img.height || 512;
        canvas.width = w;
        canvas.height = h;
        const ctx = canvas.getContext("2d", { willReadFrequently: true });
        if (!ctx) {
          resolve(imageSrc);
          return;
        }

        ctx.drawImage(img, 0, 0, w, h);
        const imgData = ctx.getImageData(0, 0, w, h);
        const data = imgData.data;

        for (let i = 0; i < data.length; i += 4) {
          const r = data[i];
          const g = data[i + 1];
          const b = data[i + 2];

          // Cold blue/purple baseline in JET composite:
          // In non-active regions, b is dominant (b >= r + 15 and b >= g - 5)
          // Active heat zones:
          // - Red / Orange / Yellow: r > b + 12
          // - Green / Lime / Cyan: g > b + 15
          const redWarmth = r - b - 12;
          const greenWarmth = g - b - 15;
          const warmthSignal = Math.max(redWarmth, greenWarmth);

          if (warmthSignal <= 0) {
            // Cold blue/purple background -> 100% transparent (no tint, no square border)
            data[i + 3] = 0;
          } else {
            // Smooth natural alpha transition entering the heat region
            const normalized = Math.min(1.0, warmthSignal / 48);
            const alpha = Math.min(255, Math.round(Math.pow(normalized, 1.1) * 255));
            
            // Keep original authentic RGB colors exactly as generated by PyTorch
            // only set the transparent alpha channel
            data[i + 3] = alpha;
          }
        }

        ctx.putImageData(imgData, 0, 0);
        const cleanDataUri = canvas.toDataURL("image/png");
        processedCache.set(imageSrc, cleanDataUri);
        resolve(cleanDataUri);
      } catch {
        resolve(imageSrc);
      }
    };
    img.onerror = () => resolve(imageSrc);
    img.src = imageSrc;
  });
}
